INSERT INTO location (city) VALUES
                                ('hanoi'),
                                ('hochiminhcity'),
                                ('haiphong'),
                                ('danang'),
                                ('cantho'),

                                ('angiang'),
                                ('bacgiang'),
                                ('backan'),
                                ('baclieu'),
                                ('bacninh'),
                                ('bentre'),
                                ('binhdinh'),
                                ('binhduong'),
                                ('binhphuoc'),
                                ('binhthuan'),

                                ('camau'),
                                ('daklak'),
                                ('daknong'),
                                ('dienbien'),
                                ('dongnai'),
                                ('dongthap'),
                                ('gialai'),
                                ('hatinh'),
                                ('haiduong'),
                                ('haugiang'),
                                ('hoabinh'),
                                ('hungyen'),
                                ('khanhhoa'),
                                ('kiengiang'),
                                ('kontum'),
                                ('laichau'),
                                ('lamdong'),
                                ('langson'),
                                ('laocai');
